accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
]
 

articles/urls.py
from django.urls import path, include
from . import views

app_name = "articles"
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>', views.follow, name='follow'),
    path('list/', views.list, name='list'),
    path('explore/', views.explore, name='explore'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    path('search/', views.search, name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
] 

articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
  content = models.TextField(unique=True)

class Article(models.Model):
  title = models.CharField(max_length=40)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True) 
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
  hashtags = models.ManyToManyField(Hashtag, blank=True)

  # 객체 표시 형식 수정
  def __str__(self):
    return f'[{self.pk}] {self.title}'


class Comment(models.Model):
  # Comment -> 이중 1:N 관계 (Article, User)
  article = models.ForeignKey(Article, on_delete=models.CASCADE)
  content = models.CharField(max_length=200)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

  # Model Level에서 메타데이터 옵션 설정 -> 정렬 가능
  class Meta:
    ordering = ['-pk',]

  def __str__(self):
    return f'[{self.pk}] {self.content}'
  

articles/forms.py
from django import forms
from .models import Article, Comment

# class ArticleForm(forms.Form):
#   title = forms.CharField(
#     # HTML tag 와 동일
#     max_length=30,
#     label='제목',
#     widget=forms.TextInput(
#       attrs={
#         'class':'title',
#         'placeholder':'제목을 입력해주세요..!',
#       }
#     )
#   )
#   # 비워둘 수 있다
#   content = forms.CharField(
#     label='내용',
#     # widget : Input Type 지정 -> Textarea / 알맞은 속성값 부여
#     widget=forms.Textarea(
#       attrs={
#         'class':'content',
#         'placeholder':'내용을 입력해주세요',
#         'rows':5,
#         'cols':30,
#       }
#     )
#   )


# ModelForm
# 1. ModelForm 클래스를 상속받아 사용한다
# 2. 메타데이터로 Model 정보를 건네주면, ModelForm이 자동으로 field에 맞춰
#   input을 생성해준다

class ArticleForm(forms.ModelForm):
  # custumizing(선택)
  title = forms.CharField(
    label='제목',
    max_length=10,
    widget=forms.TextInput(
      attrs={
        'class':'title',
        'placeholder':'제목 입력하세요..'
      }
    )
  )

  content = forms.CharField(
    label='내용',
    widget=forms.Textarea(
      attrs={
        'class':'content',
        'placeholder':'내용을 입력하세요',
        'rows':5,
        'cols':30,
      }
    )
  )


  # 메타데이터 -> 데이터의 데이터
  # ex) 사진 한장 (촬영장비이름, 촬영환경 등)
  class Meta:
    model = Article
    #fields = '__all__'
    fields = ('title','content',)




class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    # article 까지 넣어주면 사용자가 선택해서 바꿀수도 있음. 로직의 논리에 맞지 않는다!
    fields = ('content',)

 

articles/views.py
# http관련한 decorators import하기
from django.views.decorators.http import require_POST
# 장고가 기본적으로 accounts로 설정함
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect, get_object_or_404
from IPython import embed
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm
import hashlib
from itertools import chain
from django.http import JsonResponse, HttpResponseBadRequest
from django.core.paginator import Paginator
  
# Create your views here.
def index(request):
  #embed()
  # if request.user.is_authenticated:
  #   gravatar_url = hashlib.md5(request.user.email.encode('utf-8').lower().strip()).hexdigest()
  # else:
  #   gravatar_url = None

  articles = Article.objects.all()

  # 1. articles를 Paginator에 넣기
  # - Paginator(전체 리스트, 보여줄 갯수)
  paginator = Paginator(articles, 4)
  # 2. 사용자가 요청한 page 가져오기
  page = request.GET.get('page')
  # 3. 해당하는 page의 article만 가져오기
  articles = paginator.get_page(page)
  #print(dir(articles))
  #print(dir(articles.paginator))

  context = {
    'articles':articles,
    #'gravatar_url':gravatar_url,
  }
  return render(request, 'articles/index.html',context)


@login_required
#@require_POST
def create(request):
  # POST 요청 => 데이터를 받아서 DB에 저장
  if request.method == 'POST':
    # title = request.POST.get('title')
    # content = request.POST.get('content')
    # article = Article(title=title, content=content)
    # article.save()

    # Binding 과정
    # 폼 인스턴스를 생성하고, 전달받은 데이터를 채운다
    # 인스턴스에 데이터를 채워서, 유효성 검증을 진행한다
    form = ArticleForm(request.POST)
    if form.is_valid():
      article = form.save(commit=False)
      article.user = request.user
      article.save()
      # hashtag
      # 게시글 내용을 split해서 리스트로 만듦
      for word in article.content.split():
        # word가'#'으로 시작할 경우 해시태그 등록
        if word.startswith('#'):
          hashtag, created = Hashtag.objects.get_or_create(content=word)
          article.hashtags.add(hashtag)
    return redirect('articles:detail', article.pk)
  else:
    form = ArticleForm()
  
  # form으로 전달받는 형태가 2가지
  # 1. GET요청 -> 비어있는 폼 전달
  # 2. 유효성 검증 실패 -> 에러 메시지를 포함한 채로 폼 전달
  context = {'form':form }
  return render(request, 'articles/form.html', context)


def detail(request, article_pk):
  #article = Article.objects.get(pk=article_pk)
  article = get_object_or_404(Article, pk=article_pk)

  # django가 만들어준 db에서는 user_id로 만들어짐
  person = get_object_or_404(get_user_model(), pk=article.user_id)

  comment_form = CommentForm()
  comments = article.comment_set.all()
  context = {
    'article':article,
    'person':person,
    'comment_form':comment_form,
    'comments':comments,
  }
  return render(request, 'articles/detail.html', context)


# post요청만 들어올때 require_post 사용가능
#@login_required 동시에 @require_POST 사용하고 싶으면 로직내에 is_authenticated로 검증
@require_POST
def delete(request, article_pk):
  if request.user.is_authenticated:
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
    # if request.method == 'POST':
    #   article.delete()
    #   return redirect('articles:index')
    # else:
    #   return redirect('articles:detail', article.pk)
      article.delete()
    else:
      return redirect('articles:detail', article.pk)
  return redirect('articles:index')

@login_required
def update(request, article_pk):
  article= get_object_or_404(Article, pk=article_pk)
  if request.user == article.user:
    if request.method == 'POST':
      form = ArticleForm(request.POST, instance=article)
      if form.is_valid():
        # article.title = form.cleaned_data('title')
        # article.content = form.cleaned_data('content')
        article = form.save()
        # hashtag 초기화
        article.hashtags.clear()
        for word in article.content.split():
          # word가'#'으로 시작할 경우 해시태그 등록
          if word.startswith('#'):
            hashtag, created = Hashtag.objects.get_or_create(content=word)
            article.hashtags.add(hashtag)

        return redirect('articles:detail', article.pk)
    else:
      # form = ArticleForm(initial={
      #   'title':article.title,
      #   'content':article.content
      # })
      form = ArticleForm(instance=article)
      # 2가지 form 형식
      # 1. GET -> 초기값을 폼에 넣어서 사용자에게 던져줌
      # 2. POST -> is_valid가 False가 리턴됐을 때, 오류 메시지 포함해서 사용자에게 던져줌
  else:
    return redirect('articles:index')

  context = {
    'form':form, 
    'article':article 
  }
  #return render(request, 'articles/create.html', context)
  return render(request, 'articles/form.html', context)

@require_POST
def comments_create(request, article_pk):
  if request.user.is_authenticated:
    #article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
      # save() 메서드 -> 선택 인자 : (기본값) commit=True
      # comment의 article정보를 넣어줘야 하는데 정보가 없다면 일단 막아줘야한다
      # commit=False 하면 DB에 바로 저장되는 것을 막아준다. 객체 하나만 만들어진 상태
      comment = comment_form.save(commit=False)
      comment.user = request.user
      # instance를 바로 넣어주기
      #comment.article = article
      # django가 만든 db형식에 맞추어 넣어주기
      comment.article_id = article_pk
      comment.save()
  #return redirect('articles:detail', article.pk)
  return redirect('articles:detail', article_pk)



@require_POST
def comments_delete(request, article_pk, comment_pk):
  # 1. 로그인 여부 확인
  if request.user.is_authenticated:
    comment = get_object_or_404(Comment, pk=comment_pk)
    # 2. 로그인한 사용자와 댓글 작성자가 같은 경우
    if request.user == comment.user:
      comment.delete()
  return redirect('articles:detail', article_pk)


@login_required
def like(request, article_pk):  
  if request.is_ajax():
    # 좋아요 누를 게시글 가져오기
    article = get_object_or_404(Article, pk=article_pk)

    # 현재 접속하고 있는 유저
    user = request.user

    # 현재 게시글을 좋아요 누를 사람 목록에 현재 접속한
    # 유저가 있을 경우 => 좋아요 취소
    # if article.like_users.filter(pk=user.pk).exists():
    #   article.like_users.remove(user)
    # # 목록에 없을 경우 => 좋아요 누르기
    # else:
    #   article.like_users.add(user)
    if user in article.like_users.all():
      article.like_users.remove(user)
      liked = False
    else:
      article.like_users.add(user)
      liked = True

    context = {
      'liked':liked,
      'count':article.like_users.count(),
    }
    #return redirect('articles:index')
    return JsonResponse(context)
  else:
    return HttpResponseBadRequest


@login_required
def follow(request, article_pk, user_pk):
  # 게시글 작성한 유저
  person = get_object_or_404(get_user_model(), pk=user_pk)
  # 지금 접속하고 있는 유저
  user = request.user

  if person != user:
    # 게시글 작성 유저 팔로워 명단에 접속 중인 유저가 있을 경우
    # -> Unfollow
    if user in person.followers.all():
      person.followers.remove(user)

    # 명단에 없으면
    # -> Follow
    else:
      person.followers.add(user)

  # 게시글 상세정보로 redirect
  return redirect('articles:detail', article_pk)


# 내가 팔로우 하는 사람의 글 + 내가 작성한 글
def list(request):
  # 내가 팔로우하고 있는 사람들
  followings = request.user.followings.all()
  # 내가 팔로우하고 있는 사람들 + 나 => 합치기
  followings = chain(followings, [request.user])
  # 위 명단 사람들 게시글 가져오기
  # __in : 주어진 리스트 안에 존재하는 자료 검색
  articles = Article.objects.filter(user__in=followings).order_by('-pk').all()
  
  comment_form = CommentForm()

  context = {
    'articles':articles,
    'comment_form':comment_form,
  }
  return render(request, 'articles/article_list.html', context)

# 모든 사람 글
def explore(request):
  articles = Article.objects.all()
  comment_form = CommentForm()
  context = {
    'articles':articles,
    'comment_form':comment_form,
  }

  return render(request, 'articles/article_list.html', context)



# Hashtag 글 모아보기
def hashtag(request, hash_pk):
  # 해시태그 가져오기
  hashtag = get_object_or_404(Hashtag, pk=hash_pk)
  # 해당 해시태그를 참조하는 게시글들 가져오기
  articles = hashtag.article_set.order_by('-pk')
  context = {
    'hashtag':hashtag,
    'articles':articles,
  }

  return render(request, 'articles/hashtag.html', context)


def search(request):
  # 1. 사용자가 입력한 검색어 가져오기
  query = request.GET.get('query')
  # 2. DB에서 query가 포함된 제목을 가진 article 가져오기
  # orm에 LIKE와 비슷한 두가지 함수가잇다
  # __contains : 지정한 문자열 포함하는 자료 검색
  # __icontains : 지정한 문자열 포함하는 자료 검색(대소문자 구별 x)
  articles = Article.objects.filter(title__icontains=query)
  # 3. context로 전달
  context = {'articles':articles}

  return render(request, 'articles/search.html', context)

config/templates/articles/_article.html
{% comment %} <p>작성자 : {{ article.user }}</p>
<p>번호 : {{ article.pk }}
<p>제목 : {{ article.title }}</p>
<i class="far fa-kiss-wink-heart"></i>
<a href="{% url 'articles:detail' article.pk %}">[DETAIL]</a> {% endcomment %}

<!-- 모든 화면 사이즈에서 화면 2분할 -->
<div class="col-12 col-md-6 mb-3">
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">{{ article.title }}</h5>
      <p class="card-text">
        <!-- <a href="{% url 'articles:like' article.pk %}"> -->
          <!-- 사용자가 좋아요 안누른 상태 -> 빈 하트 -->
          <!-- data-id: JS가 데이터를 처리할 때 해당 요소가 
          어떤 article의 번호인지 구분하기 위해서 지정! -->
          {% if request.user in article.like_users.all %}
          <i data-id="{{ article.pk }}" class="like-button fas fa-heart" style="color:crimson; cursor:pointer;"></i>
          <!-- python list in -->
          <!-- 누른 상태 -> 꽉찬 하트 -->
          {% else %}
          <i data-id="{{ article.pk }}" class="like-button fas fa-heart" style="color:black; cursor:pointer;"></i>
          {% endif %}
        <!-- </a> -->
        <br>
        <span id="like-count-{{ article.pk }}">
          {{ article.like_users.all|length }}
        </span>
        명이 이 글을 좋아합니다 <br>
        {{ article.created_at }}
      </p>
      <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">상세보기</a>
    </div>
  </div>
</div>

config/templates/articles/_follow.html
<div class="jumbotron">
  <h1 class="display-4">{{ person.username }}</h1>
  <p class="lead">
    팔로워: {{ person.followers.all|length }}명 | 팔로잉: {{ person.followings.all|length }}명
  </p>
  <h1>팔로워 다 나와라</h1>
  {% for follower in person.followers.all %}
    {{ follower.username }}
  {% empty %}
    팔로워가 없어요..
  {% endfor %}
  <hr class="my-4">
  {% if user != article.user %}
    <a class="btn btn-primary btn-lg" href="{% url 'articles:follow' article.pk person.pk %}" role="button">
      {% if user in person.followers.all %}
        UnFollow
      {% else %}
        Follow
      {% endif %}
    </a>
  {% endif %}
</div>

config/templates/articles/_nav.html
{% load gravatar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'articles:index' %}">
    <img class="rounded-circle mr-2" src="https://s.gravatar.com/avatar/{{ user.email|makemd5 }}?s=80&d=mp" alt="">
    Hello, {{ user.username }}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'articles:list' %}">좋은글보기</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'articles:explore' %}">전부보기</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:profile' user.username %}">마이페이지</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:update' %}">정보수정</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:change_password' %}">암호변경</a>
        </li>
        <form action="{% url 'accounts:delete' %}" method="POST" style="display: inline;">
          {% csrf_token %}
          <input type="submit" value="회원탈퇴" class="btn btn-danger">
        </form>
      <!-- 비회원일 경우 -->
      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</span></a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

config/templates/articles/article_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
  <!-- URL Resolver를 사용해서 제목값 분기 -->
  {% if request.resolver_match.url_name == 'list' %}
    <h1>List</h1>
  {% else %}
    <h1>Explore</h1>
  {% endif %}
  <hr>
  {% for article in articles %}
    <p>글 제목: {{ article.title }}</p>
    <p>글 내용: {{ article.content }}</p>
    <hr>
    <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
      {% csrf_token %}
      {% bootstrap_form comment_form %}
      {% buttons submit='댓글작성' %}{% endbuttons %}
    </form>
    <hr>
  {% endfor %}
{% endblock  %}

config/templates/articles/detail.html
{% extends 'base.html' %}
{% load make_link %}

{% block body %}
{% include 'articles/_follow.html' %}

<h1>DETAIL</h1>
<label for="pk">PK</label>
<p>{{ article.pk }}</p>
<label for="title">TITLE</label>
<p>{{ article.title }}</p>
<label for="content">CONTENT</label>
<!-- <p>{{ article.content }}</p> -->
<!-- tag 적용되도록 escape을 방지해주는 django template tag -->
<!-- https://docs.djangoproject.com/en/2.2/ref/templates/builtins/ -->
<p>{{ article|hashtag_link|safe }}</p>
<hr>
<a href="{% url 'articles:index' %}">[HOME]</a>
{% if request.user == article.user %}
  <form action="{% url 'articles:update' article.pk %}" method="GET">
    <input type="submit" value="[EDIT]">
  </form>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="[DELETE]">
  </form>
{% endif %}

<hr>
{% if user.is_authenticated %}
  <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="댓글작성">
  </form>
{% else %}
  <a href="{% url 'accounts:login' %}">[댓글 작성하려면 로그인 해주세요]</a>
{% endif %}
<hr>
<p><b>댓글 목록({{ comments|length }})개</b></p>
{% for comment in comments %}
<!-- forloop.counter : for문 순서, forloop.revcounter : 역순 -->
  <p style="display:inline">[{{ forloop.revcounter }}번댓글] {{ comment.content }}
  {% if request.user == comment.user %}
    <form style="display:inline" action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제" onClick="return confirm('정말 삭제하겠습니까?')">
    </form>  
  {% endif %}
  </p>
{% endfor %}
{% endblock  %}

config/templates/articles/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if request.resolover_match.url_name == 'create' %}
  <h1 class="text-center">CREATE</h1>
{% else %}
  <h1 class="text-center">UPDATE</h1>
{% endif %}
<!-- <form action="{% url 'articles:create' %}" method="POST"></form> -->
<!-- RESTful하게 통합했으면 form action은 get요청을 보낸 주소로 보내진다 -->
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form layout='inline' %}
<!-- 각각의 input 태그를 p태그로 감싸라-->  
  {% comment %} {{ form.as_p }} {% endcomment %}
  <!-- <input type="submit" value="등록☆"> -->
  <div class="text-center">
    {% buttons submit='제출' reset='초기화' %}
    {% endbuttons %}
  </div>
</form>
<hr>
{% if request.resolver_match.url_name == 'create' %}
  <a href="{% url 'articles:index' %}">[BACK]</a>
{% else %}
  <a href="{% url 'articles:detail' article.pk %}">[BACK]</a>
{% endif %}

{% endblock  %}

config/templates/articles/hashtag.html
{% extends 'base.html' %}
{% block body %}
<h1>{{ hashtag.content }} 게시글 모아보기</h1>
<h4>{{ articles|length }}개의 글이 있습니다</h4>
<hr>
{% for article in articles %}
  <p>글 제목 : {{ article.title }}</p>
  <p>글 내용 : {{ article.content }}</p>
  <!-- article과 comment는 1:N 관계 -->
  <p>{{ article.comment_set.all|length }}개의 댓글이 있습니다.</p>
  <!-- article과 like_users는 M:N 관계, user_set을 like_users로 커스터마이징해준것 -->
  <p>{{ article.like_users.all|length }}명이 이 글을 좋아합니다</p>
{% endfor %}
{% endblock  %}

config/templates/articles/index.html
{% extends 'base.html' %}

{% block body %}
<h1>Articles</h1>
<a href="{% url 'articles:create' %}">New</a>
<hr>

<form class="mb-4" action="{% url 'articles:search' %}"><!-- margin bottom -->
  <div class="form-row justify-content-center">
    <div class="mb-2 col-12 col-sm-9 col-md-10">
      <input type="text" name="query" class="form-control" placeholder="제목을 입력해주세요">
    </div>
    <div class="col-8 col-sm-3 col-md-2">
      <input type="submit" class="form-control btn btn-success" value="검색">
    </div>
  </div>
</form>

<!-- base.html 에 container 클래스 안에잇음 -->
<div class="row">
  {% for article in articles %}
    <!-- 모듈화 시켜둔 article 템플릿 가져오기 -->
    {% include 'articles/_article.html' %}

  {% comment %} <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제" onClick="return confirm('정말 삭제하겠습니까?')">
  </form>
  </p> {% endcomment %}
  <hr>
  {% endfor %}
</div>

<!--<h1>{{ articles.paginator.page_range }}</h1> -->
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
  <!-- 이전 페이지가 있을 경우 -->
    {% if articles.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{% url 'articles:index' %}?page={{ articles.previous_page_number }}" tabindex="-1" aria-disabled="true">◀</a>
    </li>
    {% endif %}

    <!-- 페이지 버튼 -->
    {% for num in articles.paginator.page_range %}
    <li class="page-item {% if num ==  articles.number %}active{% endif %}">
      <a class="page-link" href="{% url 'articles:index' %}?page={{ num }}">{{ num }}</a>
    </li>
    {% endfor %}
    <!-- 다음 페이지 있으면 Next 버튼 출력 -->
    {% if articles.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% url 'articles:index' %}?page={{ articles.next_page_number }}">▶</a>
    </li>
    {% endif %}
  </ul>
</nav>

<script>
  // 1. 모든 좋아요 버튼 가져오기
  const likeButtons = document.querySelectorAll('.like-button')

  // 2. forEach 함수 활용 => 각각의 좋아요 버튼 클릭햇을 떄
  likeButtons.forEach(button => {
    button.addEventListener('click', function(event){
      console.log(event)
      // event.target.classList, event.target.dataset.id
      // 1. data-id 에 article.pk가 들어있음 => 동적 라우팅 활용!
      const articleId = event.target.dataset.id

      // 장고가 Ajax 요청을 구분하게 하기 위해서 XHR 객체를 담아서 보내준다
      axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
      axios.defaults.xsrfCookieName = 'csrftoken'
      axios.defaults.xsrfHeaderName = 'X-CSRFToken'
      // 2. 해당 게시글의 좋아요 요청 보내기
      // axios.get(`/articles/${articleId}/like`)

      {% if user.is_authenticated %}
      axios.post(`/articles/${articleId}/like/`)
        .then(response => {
          //console.log(response)
          console.log(response.data)
          // 알맞은 id값을 가지 span 태그를 선택해서, 
          // 사용자가 좋아요 누를 때마다 response.data.count 값으로 갱신시킨다
          document.querySelector(`#like-count-${articleId}`) //span 태그 선택
          .innerText = response.data.count
      
          if (response.data.liked){
            event.target.style.color = 'crimson'
          }else{
            event.target.style.color = 'black'
          }
        })
        .catch(error =>  {console.log(error) })
        {% else %}
          alert('로그인을 해야 기능을 사용할 수 있습니다')
        {% endif %}
    })
  })
</script>

{% endblock  %} 

config/templates/articles/search.html
{% extends 'base.html' %}

{% block body %}
<h1>검색 결과</h1>
<hr>
  <ul class="list-group">
    {% for article in articles %}
      <a href="{% url 'articles:detail' article.pk %}" class="mb-2">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        [{{ forloop.counter }}] {{ article.title }}
        <span class="badge badge-warning badge-pill">
          {{ article.comment_set.all|length }}
        </span>
      </li>
    </a>
    {% endfor %}
  </ul>
{% endblock  %}