accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('<str:username>/', views.profile, name='profile'),
]
 

articles/urls.py
from django.urls import path, include
from . import views

app_name = "articles"
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/follow/<int:user_pk>', views.follow, name='follow'),
    path('list/', views.list, name='list'),
    path('explore/', views.explore, name='explore'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    path('search/', views.search, name='search'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
] 

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
  followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
  content = models.TextField(unique=True)

class Article(models.Model):
  title = models.CharField(max_length=40)
  content = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True) 
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)
  hashtags = models.ManyToManyField(Hashtag, blank=True)

  # 객체 표시 형식 수정
  def __str__(self):
    return f'[{self.pk}] {self.title}'


class Comment(models.Model):
  # Comment -> 이중 1:N 관계 (Article, User)
  article = models.ForeignKey(Article, on_delete=models.CASCADE)
  content = models.CharField(max_length=200)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

  # Model Level에서 메타데이터 옵션 설정 -> 정렬 가능
  class Meta:
    ordering = ['-pk',]

  def __str__(self):
    return f'[{self.pk}] {self.content}'
  

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

# UserChangeForm상속받아서 customizing
class CustomUserChangeForm(UserChangeForm):
  class Meta:
    # User 클래스를 바로 가져와서 사용하는 것이 아니라 
    # get_user_model()을 사용해서 User 클래스를 참조
    model = get_user_model()
    # UserChangeForm => User 클래스 => AbstractUser 클래스 상속 순
    # 이정도만 사용자가 수정할 수 있도록 변경
    # Django 공식문서 : user-model
    fields = ('email', 'last_name', 'first_name',)


class CustomUserCreationForm(UserCreationForm):
  class Meta:
    model = get_user_model()
    fields = ('username', 'password1', 'password2', 'email', )

accounts/views.py
from IPython import embed
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST

from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required

# Authentication(인증) -> 신원 확인
# - 자신이 누구라고 주장하는 사람의 신원을 확인하는 것

# Create your views here.

# Auth CRUD : CREATE
def signup(request):
  if request.user.is_authenticated:
    return redirect('articles:index')
  if request.method == 'POST':
    form = CustomUserCreationForm(request.POST)
    #embed()
    if form.is_valid():
      user = form.save()
      auth_login(request, user)
      return redirect('articles:index')
  else:
    form = CustomUserCreationForm()

  context = {'form':form}
  return render(request, 'accounts/auth_form.html', context) 


def login(request):
  #embed()
  # 이미 login되어있는 사용자가 다시 로그인 시도할때
  if request.user.is_authenticated:
    return redirect('articles:index')
 
  if request.method == 'POST':
    # login은 session 정보가 있기때문에 request 넘겨줘야함
    form = AuthenticationForm(request, request.POST)
    #embed()
    if form.is_valid():
      # AuthenticationForm이 들고잇는 사용자 정보를 들고온다
      auth_login(request, form.get_user())
      #return redirect('articles:index')
      return redirect(request.GET.get('next') or 'articles:index')
  else:
    form = AuthenticationForm()
  
  context = { 'form':form }
  return render(request, 'accounts/login.html', context)


def logout(request):
  # 이서버에서 보고 있는 session에서 login 정보를 지워버림
  auth_logout(request)
  return redirect('articles:index')

@require_POST
def delete(request):
  # 지금 접속하고 있는 user 바로 삭제
  request.user.delete()
  return redirect('articles:index')

# 회원정보 수정
@login_required
def update(request):
  if request.method == 'POST':
    form = CustomUserChangeForm(request.POST, instance=request.user)
    if form.is_valid():
      form.save()
      return redirect('articles:index')
  else:
    form = CustomUserChangeForm(instance=request.user)
  context = {'form':form}
  return render(request, 'accounts/auth_form.html', context)

@login_required
def change_password(request):
  if request.method == 'POST':
    form = PasswordChangeForm(request.user, request.POST)
    if form.is_valid():
      user = form.save()
      update_session_auth_hash(request,user)
      return redirect('articles:index')
  else:
    form = PasswordChangeForm(request.user)
  context = {'form':form}
  return render(request, 'accounts/auth_form.html', context)


def profile(request, username):
  person = get_object_or_404(get_user_model(), username=username)
  context = {'person':person}
  return render(request, 'accounts/profile.html', context)

config/templates/accounts/auth_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
{% if request.resolver_match.url_name == 'signup' %}
  <h1>회원가입</h1>
{% elif request.resolver_match.url_name == 'login' %}
  <h1>로그인</h1>
{% elif request.resolver_match.url_name == 'update' %}
  <h1>회원정보수정</h1>
{% else %}
  <h1>비밀번호변경</h1>
{% endif %}
<hr>
<form action="" method="POST">
  {% csrf_token %}
<!-- {{ form.as_p }} -->  
  {% bootstrap_form form layout='inline' %}
  {% buttons submit='가입' reset='초기화' %}
  {% endbuttons %}
</form>
{% endblock  %} 

config/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
<h1>암호변경</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='변경하기' reset='초기화' %}
  {% endbuttons %}
</form>

{% endblock  %}

config/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load socialaccount %}

{% block body %}

<form action="" method="POST">
  {% csrf_token %}
<!-- {{ form.as_p }} -->  
  {% bootstrap_form form %}
  {% buttons submit='로그인' reset='초기화' %}
  {% endbuttons %}
  <a href="{% provider_login_url 'kakao' %}" class="btn btn-warning">카카오 로그인</a>
</form>
{% endblock  %} 

config/templates/accounts/profile.html
{% extends 'base.html' %}

{% block body %}
<h1>{{ person.username }}님의 Profile</h1>
<hr>
<h3>{{ person.username }}님이 작성한 게시글</h3>
<div class="row">
  {% for article in person.article_set.all %}
    <div class="col-12 col-md-6 mb-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ article.title }}</h5>
          <p class="card-text">
          <a href="{% url 'articles:like' article.pk %}">
            <!-- 사용자가 좋아요 안누른 상태 -> 빈 하트 -->
            {% if request.user in article.like_users.all %}
              <i class="fas fa-kiss-wink-heart"></i>
            <!-- python list in -->
            <!-- 누른 상태 -> 꽉찬 하트 -->
            {% else %}
              <i class="far fa-kiss-wink-heart"></i>
            {% endif %}
          </a>
            {{ article.like_users.all|length }}명이 이 글을 좋아합니다 <br>
            {{ article.created_at }}
          </p>
          <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">상세보기</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
<h3>{{ person.username }}님이 작성한 댓글</h3>
<div class="row">
  {% for comment in person.comment_set.all %}
    <div class="col-12 col-md-6">
      <div class="card">
        <div class="card-header">
          Featured
        </div>
        <div class="card-body">
          <h5 class="card-title">
            {{ comment.content }}
          </h5>
          <p class="card-text">
            {{ comment.created_at|date:"SHORT_DATETIME_FORMAT" }}
          </p>
          <a href="{% url 'articles:detail' comment.article.pk %}" class="btn btn-primary">게시글 확인</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>
{% endblock  %}